[commands.eslint]
type = "lint"
cmd = ["pnpm", "exec", "eslint"]
invoke = "once"
include = ["src/**/*.ts"]
ok-exit-codes = 0

[commands.tsc]
type = "lint"
cmd = ["pnpm", "exec", "tsc", "--noEmit"]
invoke = "once"
path-args = "none"
include = ["src/**/*.ts", "tsconfig.json"]
ok-exit-codes = 0

[commands.prettier]
type = "both"
cmd = ["pnpm", "exec", "prettier", "--parser", "typescript"]
lint-flags = ["--check"]
tidy-flags = ["--write"]
path-args = "absolute-file"
include = ["src/**/*.ts"]
ok-exit-codes = 0
